//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("sepModel", "d", "group_visitor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SEP_ASS3.group_visitor), "visitor_track", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SEP_ASS3.visitor_track), true)]
[assembly: EdmRelationshipAttribute("sepModel", "ddd", "group_visitor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SEP_ASS3.group_visitor), "visitor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SEP_ASS3.visitor), true)]
[assembly: EdmRelationshipAttribute("sepModel", "s", "track", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SEP_ASS3.track), "visitor_track", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SEP_ASS3.visitor_track), true)]

#endregion

namespace SEP_ASS3
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sepEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sepEntities2 object using the connection string found in the 'sepEntities2' section of the application configuration file.
        /// </summary>
        public sepEntities2() : base("name=sepEntities2", "sepEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sepEntities2 object.
        /// </summary>
        public sepEntities2(string connectionString) : base(connectionString, "sepEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sepEntities2 object.
        /// </summary>
        public sepEntities2(EntityConnection connection) : base(connection, "sepEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<group_visitor> group_visitor
        {
            get
            {
                if ((_group_visitor == null))
                {
                    _group_visitor = base.CreateObjectSet<group_visitor>("group_visitor");
                }
                return _group_visitor;
            }
        }
        private ObjectSet<group_visitor> _group_visitor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<park_ranger> park_ranger
        {
            get
            {
                if ((_park_ranger == null))
                {
                    _park_ranger = base.CreateObjectSet<park_ranger>("park_ranger");
                }
                return _park_ranger;
            }
        }
        private ObjectSet<park_ranger> _park_ranger;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<track> track
        {
            get
            {
                if ((_track == null))
                {
                    _track = base.CreateObjectSet<track>("track");
                }
                return _track;
            }
        }
        private ObjectSet<track> _track;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<visitor> visitor
        {
            get
            {
                if ((_visitor == null))
                {
                    _visitor = base.CreateObjectSet<visitor>("visitor");
                }
                return _visitor;
            }
        }
        private ObjectSet<visitor> _visitor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<visitor_track> visitor_track
        {
            get
            {
                if ((_visitor_track == null))
                {
                    _visitor_track = base.CreateObjectSet<visitor_track>("visitor_track");
                }
                return _visitor_track;
            }
        }
        private ObjectSet<visitor_track> _visitor_track;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the group_visitor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogroup_visitor(group_visitor group_visitor)
        {
            base.AddObject("group_visitor", group_visitor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the park_ranger EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopark_ranger(park_ranger park_ranger)
        {
            base.AddObject("park_ranger", park_ranger);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the track EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotrack(track track)
        {
            base.AddObject("track", track);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the visitor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovisitor(visitor visitor)
        {
            base.AddObject("visitor", visitor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the visitor_track EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovisitor_track(visitor_track visitor_track)
        {
            base.AddObject("visitor_track", visitor_track);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sepModel", Name="group_visitor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_visitor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new group_visitor object.
        /// </summary>
        /// <param name="group_id">Initial value of the group_id property.</param>
        public static group_visitor Creategroup_visitor(global::System.String group_id)
        {
            group_visitor group_visitor = new group_visitor();
            group_visitor.group_id = group_id;
            return group_visitor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String group_id
        {
            get
            {
                return _group_id;
            }
            set
            {
                if (_group_id != value)
                {
                    Ongroup_idChanging(value);
                    ReportPropertyChanging("group_id");
                    _group_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("group_id");
                    Ongroup_idChanged();
                }
            }
        }
        private global::System.String _group_id;
        partial void Ongroup_idChanging(global::System.String value);
        partial void Ongroup_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> startTime
        {
            get
            {
                return _startTime;
            }
            set
            {
                OnstartTimeChanging(value);
                ReportPropertyChanging("startTime");
                _startTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startTime");
                OnstartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _startTime;
        partial void OnstartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnstartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> endTime
        {
            get
            {
                return _endTime;
            }
            set
            {
                OnendTimeChanging(value);
                ReportPropertyChanging("endTime");
                _endTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endTime");
                OnendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _endTime;
        partial void OnendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnendTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private Nullable<global::System.Int32> _duration;
        partial void OndurationChanging(Nullable<global::System.Int32> value);
        partial void OndurationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sepModel", "d", "visitor_track")]
        public EntityCollection<visitor_track> visitor_track
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<visitor_track>("sepModel.d", "visitor_track");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<visitor_track>("sepModel.d", "visitor_track", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sepModel", "ddd", "visitor")]
        public EntityCollection<visitor> visitor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<visitor>("sepModel.ddd", "visitor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<visitor>("sepModel.ddd", "visitor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sepModel", Name="park_ranger")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class park_ranger : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new park_ranger object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static park_ranger Createpark_ranger(global::System.Int32 id)
        {
            park_ranger park_ranger = new park_ranger();
            park_ranger.ID = id;
            return park_ranger;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String businessPhone
        {
            get
            {
                return _businessPhone;
            }
            set
            {
                OnbusinessPhoneChanging(value);
                ReportPropertyChanging("businessPhone");
                _businessPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("businessPhone");
                OnbusinessPhoneChanged();
            }
        }
        private global::System.String _businessPhone;
        partial void OnbusinessPhoneChanging(global::System.String value);
        partial void OnbusinessPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dob
        {
            get
            {
                return _dob;
            }
            set
            {
                OndobChanging(value);
                ReportPropertyChanging("dob");
                _dob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dob");
                OndobChanged();
            }
        }
        private Nullable<global::System.DateTime> _dob;
        partial void OndobChanging(Nullable<global::System.DateTime> value);
        partial void OndobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sepModel", Name="track")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class track : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new track object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static track Createtrack(global::System.Int32 id)
        {
            track track = new track();
            track.ID = id;
            return track;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String startPoint
        {
            get
            {
                return _startPoint;
            }
            set
            {
                OnstartPointChanging(value);
                ReportPropertyChanging("startPoint");
                _startPoint = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("startPoint");
                OnstartPointChanged();
            }
        }
        private global::System.String _startPoint;
        partial void OnstartPointChanging(global::System.String value);
        partial void OnstartPointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String destination
        {
            get
            {
                return _destination;
            }
            set
            {
                OndestinationChanging(value);
                ReportPropertyChanging("destination");
                _destination = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("destination");
                OndestinationChanged();
            }
        }
        private global::System.String _destination;
        partial void OndestinationChanging(global::System.String value);
        partial void OndestinationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> visitedTime
        {
            get
            {
                return _visitedTime;
            }
            set
            {
                OnvisitedTimeChanging(value);
                ReportPropertyChanging("visitedTime");
                _visitedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("visitedTime");
                OnvisitedTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _visitedTime;
        partial void OnvisitedTimeChanging(Nullable<global::System.Int32> value);
        partial void OnvisitedTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> overdueTime
        {
            get
            {
                return _overdueTime;
            }
            set
            {
                OnoverdueTimeChanging(value);
                ReportPropertyChanging("overdueTime");
                _overdueTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("overdueTime");
                OnoverdueTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _overdueTime;
        partial void OnoverdueTimeChanging(Nullable<global::System.Int32> value);
        partial void OnoverdueTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private Nullable<global::System.Int32> _duration;
        partial void OndurationChanging(Nullable<global::System.Int32> value);
        partial void OndurationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sepModel", "s", "visitor_track")]
        public EntityCollection<visitor_track> visitor_track
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<visitor_track>("sepModel.s", "visitor_track");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<visitor_track>("sepModel.s", "visitor_track", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sepModel", Name="visitor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class visitor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new visitor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static visitor Createvisitor(global::System.String id)
        {
            visitor visitor = new visitor();
            visitor.ID = id;
            return visitor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contactNumber
        {
            get
            {
                return _contactNumber;
            }
            set
            {
                OncontactNumberChanging(value);
                ReportPropertyChanging("contactNumber");
                _contactNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contactNumber");
                OncontactNumberChanged();
            }
        }
        private global::System.String _contactNumber;
        partial void OncontactNumberChanging(global::System.String value);
        partial void OncontactNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dob
        {
            get
            {
                return _dob;
            }
            set
            {
                OndobChanging(value);
                ReportPropertyChanging("dob");
                _dob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dob");
                OndobChanged();
            }
        }
        private Nullable<global::System.DateTime> _dob;
        partial void OndobChanging(Nullable<global::System.DateTime> value);
        partial void OndobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> signedOut
        {
            get
            {
                return _signedOut;
            }
            set
            {
                OnsignedOutChanging(value);
                ReportPropertyChanging("signedOut");
                _signedOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("signedOut");
                OnsignedOutChanged();
            }
        }
        private Nullable<global::System.Boolean> _signedOut;
        partial void OnsignedOutChanging(Nullable<global::System.Boolean> value);
        partial void OnsignedOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isoverdue
        {
            get
            {
                return _isoverdue;
            }
            set
            {
                OnisoverdueChanging(value);
                ReportPropertyChanging("isoverdue");
                _isoverdue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isoverdue");
                OnisoverdueChanged();
            }
        }
        private Nullable<global::System.Boolean> _isoverdue;
        partial void OnisoverdueChanging(Nullable<global::System.Boolean> value);
        partial void OnisoverdueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String medicalDetails
        {
            get
            {
                return _medicalDetails;
            }
            set
            {
                OnmedicalDetailsChanging(value);
                ReportPropertyChanging("medicalDetails");
                _medicalDetails = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("medicalDetails");
                OnmedicalDetailsChanged();
            }
        }
        private global::System.String _medicalDetails;
        partial void OnmedicalDetailsChanging(global::System.String value);
        partial void OnmedicalDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String group_id
        {
            get
            {
                return _group_id;
            }
            set
            {
                Ongroup_idChanging(value);
                ReportPropertyChanging("group_id");
                _group_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("group_id");
                Ongroup_idChanged();
            }
        }
        private global::System.String _group_id;
        partial void Ongroup_idChanging(global::System.String value);
        partial void Ongroup_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> mailSent
        {
            get
            {
                return _mailSent;
            }
            set
            {
                OnmailSentChanging(value);
                ReportPropertyChanging("mailSent");
                _mailSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mailSent");
                OnmailSentChanged();
            }
        }
        private Nullable<global::System.Boolean> _mailSent;
        partial void OnmailSentChanging(Nullable<global::System.Boolean> value);
        partial void OnmailSentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sepModel", "ddd", "group_visitor")]
        public group_visitor group_visitor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_visitor>("sepModel.ddd", "group_visitor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_visitor>("sepModel.ddd", "group_visitor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<group_visitor> group_visitorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_visitor>("sepModel.ddd", "group_visitor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<group_visitor>("sepModel.ddd", "group_visitor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sepModel", Name="visitor_track")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class visitor_track : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new visitor_track object.
        /// </summary>
        /// <param name="group_ID">Initial value of the group_ID property.</param>
        /// <param name="track_ID">Initial value of the track_ID property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static visitor_track Createvisitor_track(global::System.String group_ID, global::System.Int32 track_ID, global::System.Int32 id)
        {
            visitor_track visitor_track = new visitor_track();
            visitor_track.group_ID = group_ID;
            visitor_track.track_ID = track_ID;
            visitor_track.ID = id;
            return visitor_track;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String group_ID
        {
            get
            {
                return _group_ID;
            }
            set
            {
                Ongroup_IDChanging(value);
                ReportPropertyChanging("group_ID");
                _group_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("group_ID");
                Ongroup_IDChanged();
            }
        }
        private global::System.String _group_ID;
        partial void Ongroup_IDChanging(global::System.String value);
        partial void Ongroup_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 track_ID
        {
            get
            {
                return _track_ID;
            }
            set
            {
                Ontrack_IDChanging(value);
                ReportPropertyChanging("track_ID");
                _track_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("track_ID");
                Ontrack_IDChanged();
            }
        }
        private global::System.Int32 _track_ID;
        partial void Ontrack_IDChanging(global::System.Int32 value);
        partial void Ontrack_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sepModel", "d", "group_visitor")]
        public group_visitor group_visitor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_visitor>("sepModel.d", "group_visitor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_visitor>("sepModel.d", "group_visitor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<group_visitor> group_visitorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_visitor>("sepModel.d", "group_visitor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<group_visitor>("sepModel.d", "group_visitor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sepModel", "s", "track")]
        public track track
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<track>("sepModel.s", "track").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<track>("sepModel.s", "track").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<track> trackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<track>("sepModel.s", "track");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<track>("sepModel.s", "track", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
